// import type {Metadata} from 'next'
"use client"
import {Inter} from 'next/font/google'
import './globals.css'
import {Provider} from "react-redux";
import {store} from "~/services/store";

const inter = Inter({subsets: ['latin']})

// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// }

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={`bg-black w-full h-full flex justify-center items-center ${inter.className}`} suppressHydrationWarning>
        <Provider store={store}>
            {children}
        </Provider>
        </body>
        </html>
    )
}
