// import type {Metadata} from 'next'
"use client"
import {Inter} from 'next/font/google'
import './globals.css'
import 'react-toastify/dist/ReactToastify.css';
import {QueryClient, QueryClientProvider} from "@tanstack/react-query";
import {useRouter} from "next/navigation";
import {useEffect} from "react";


const inter = Inter({subsets: ['latin']})
// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// }
const queryClient = new QueryClient({
    defaultOptions: {
        queries: {
            refetchOnWindowFocus: false, // default: true
        },
    },
})

export default function RootLayout({children,}: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body className={`bg-black w-full h-full flex justify-center items-center ${inter.className}`} suppressHydrationWarning>
            <QueryClientProvider client={queryClient}>
                {children}
            </QueryClientProvider>
        </body>
        </html>
    )
}
